version: '3.7'

services:
    nodeapp:
        container_name: node_pdf
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "80:80"
        links:
            - mongodb
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        networks:
            - node-webapp-network
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: stocks
        networks:
          - node-webapp-network
        ports:
            - 27017:27017
        volumes:
            - ~/mongo:/data/db
networks:
  node-webapp-network:
    driver: bridge